x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - capabilities: [gpu]

services:
  ollama:
    <<: *x-gpu
    image: ollama/ollama:latest
    environment:
      OLLAMA_DEBUG: 1
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  ollama:
    # Without options it creates a new volume with project prefix
    # Uncomment the following lines to use a named
    # volume to share with other projects:
    #
    # external: true
    # name: pfad_ollama
  qdrant_storage: